[project]
name = "ngff-zarr-ts"
version = "0.1.0"
description = "TypeScript implementation of ngff-zarr for Deno, Node, and the browser."
authors = ["Matt McCormick <matt@fideus.io>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
deno = "*"

[tasks]
dev = "deno run --allow-all src/mod.ts"
test = "deno test --allow-all --ignore=test/browser-npm/"
lint = "deno lint"
fmt = "deno fmt"
check = "deno check src/mod.ts"
build = "deno run --allow-all scripts/build.ts"

[tasks.fmt-check]
cmd = "deno fmt --check"

[tasks.lint-check]
cmd = "deno lint"

[tasks.typecheck]
cmd = "deno check src/mod.ts"

[tasks.test-watch]
cmd = "deno test --allow-all --ignore=test/browser-npm/ --watch"

[tasks.build-npm]
cmd = "deno run --allow-all scripts/build_npm.ts"

[tasks.test-browser]
cmd = "node scripts/run_playwright.mjs"

[tasks.test-browser-ui]
cmd = "node scripts/run_playwright.mjs --ui"

[tasks.test-browser-npm]
cmd = "deno run --allow-all scripts/build_npm.ts && node scripts/run_playwright.mjs"

[tasks.test-all]
cmd = "deno test --allow-all --ignore=test/browser-npm/ && deno run --allow-all scripts/build_npm.ts && node scripts/run_playwright.mjs"

[tasks.test-deno]
cmd = "which deno && deno --version"