[project]
name = "ngff-zarr-ts"
version = "0.1.0"
description = "TypeScript implementation of ngff-zarr for Deno and npm"
authors = ["ngff-zarr contributors"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
deno = ">=1.40.0"

[tasks]
dev = "deno run --allow-all src/mod.ts"
test = "deno test --allow-all"
lint = "deno lint"
fmt = "deno fmt"
check = "deno check src/mod.ts"
build = "deno run --allow-all scripts/build.ts"

[tasks.fmt-check]
cmd = "deno fmt --check"

[tasks.lint-check]
cmd = "deno lint"

[tasks.typecheck]
cmd = "deno check src/mod.ts"

[tasks.test-watch]
cmd = "deno test --allow-all --watch"

[tasks.build-npm]
cmd = "deno run --allow-all scripts/build_npm.ts"