[project]
name = "ngff-zarr-ts"
version = "0.1.0"
description = "TypeScript implementation of ngff-zarr for Deno, Node, and the browser."
authors = ["Matt McCormick <matt@fideus.io>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]

[tasks]
dev = "deno run --allow-all src/mod.ts"
test = "deno test --allow-all --ignore=test/browser-npm/"
lint = "deno lint"
fmt = "deno fmt"
check = "deno check src/mod.ts"
build = "deno run --allow-all scripts/build.ts"

[tasks.fmt-check]
cmd = "deno fmt --check"

[tasks.typecheck]
cmd = "deno check src/mod.ts"

[tasks.dev-server]
cmd = "deno run --allow-all test/browser/server.ts"

[tasks.test-browser]
cmd = "node scripts/run_playwright.mjs"

[tasks.test-browser-ui]
cmd = "node scripts/run_playwright.mjs --ui"

[tasks.test-browser-debug]
cmd = "node scripts/run_playwright.mjs --debug"

[tasks.test-browser-bundle]
cmd = "deno task build:bundle && deno task test:browser"

[tasks.test-browser-npm]
cmd = "deno task build:npm && deno task test:browser"

[tasks.test-all]
cmd = "deno task test && deno task test:browser:bundle"

[tasks.build-npm]
cmd = "deno run --allow-all scripts/build_npm.ts"

[tasks.build-bundle]
cmd = "deno bundle --platform=browser --format=esm --minify -o test/browser-npm/ngff-zarr.bundle.js src/browser-mod.ts"