name: MCP CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.49.0
        manifest-path: ./mcp/pyproject.toml
        cache: true

    - name: Install dependencies
      working-directory: ./mcp
      run: pixi install

    - name: Run linting
      working-directory: ./mcp
      run: pixi run -e dev lint

    - name: Run type checking
      working-directory: ./mcp
      run: pixi run -e dev typecheck

    - name: Run tests
      working-directory: ./mcp
      run: pixi run -e dev test-cov

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
      with:
        fail_ci_if_error: true
